In [2]:
import numpy as np

In [3]:
a = np.array([[1, -2], [-1, 3]])
b = np.zeros_like(a)
c = np.maximum(a, b)
d = np.negative(a)
e = 1 / (1+np.exp(d))


In [5]:
from per1grad.function import Function as f 
from per1grad.buffer import Buffer 
from per1grad.ops import Ops

pa = Buffer(a)
pb = Buffer(e)
pc = pa.doop(Ops.ADD, pb)
pc = f.relu(pc)
pc

per1grad buffer:
 [[1.73105858 0.        ]
 [0.         3.95257413]]

In [10]:
from per1grad.tensor import Tensor
import numpy as np 

a = np.array([[2, 1], [-1, 3]])
ta = Tensor(a)
copy_ta = Tensor(ta, ta)


TypeError: Tensor.__init__() takes 2 positional arguments but 3 were given

In [1]:
from per1grad.buffer import Buffer

import numpy as np 
a = np.array([[1, 2], [2, 3]])
b = np.array([[2, 3], [2, 2]])
c = np.array([a, b])
ba = Buffer(a)
bb = Buffer(b)
bc = Buffer([ba, bb])
print(c)
print(bc._np)

[[[1 2]
  [2 3]]

 [[2 3]
  [2 2]]]
[[[1 2]
  [2 3]]

 [[2 3]
  [2 2]]]
